export const CONFIG = {
  wifeName: "Pamela",
};

export const ENTRIES = [
  {
    name: "Chasity Johnson",
    promptIdx: 2,
    bookTitle: "The Day We Learned to Fly",
    bookAuthor: "Jacqueline Woodson",
    videoUrl: "https://drive.google.com/file/d/1c6MdO7JOehhUbDwDd_AzHBNWLxOIAMRd/view?usp=share_link",
    note: "We have walked, talked, ran, crawled and danced through chapters 12-44 but in these next chapters of our life together, He's doing a new thing. Let's go!",
  },
  {
    name: "Bren",
    promptIdx: 1,
    bookTitle: "When We Talk to God",
    bookAuthor: "Sharifa Stevens",
    videoUrl: "https://drive.google.com/file/d/1UMrMIB_HwG5JnO_hbUwU38PpPC2wwdsu/view?usp=share_link",
    note: "We often end up here: in spaces or moments that require us to talk to God.",
  },
  {
    name: "Tiff Griff",
    promptIdx: 3,
    bookTitle: "No Mud, No Lotus",
    bookAuthor: "Thich Nhat Hanh",
    videoUrl: "https://drive.google.com/file/d/1Fu61Y_7dVDz3zdC-oZKJuw2YXGGmXwMm/view?usp=share_link",
    note: "We can not choose our parents, our siblings or the situations into which we were born. We also cannot choose many of the circumstances that we face day in and day out. What we CAN choose however is how we react, how we transform, what we DO with the adversity, the suffering, the pain, the misfortunes and the hurt. This book is all about transformation. Not running from the suffering of life, but USING it to be more compassionate, to build, to create and of course to love. Beautiful lotuses CAN NOT grow in clear water. Their beauty emerges from muddy water, a stunning reminder that joy can come from, and is often just on the other side of, the ick. I don't know everything about Pam's life of course, but from what I do know, she is the embodiment of transforming mud into the good, the righteous, the beauty, the light and the joy and the laughter and the fun and the wholesome. I hope she loves this book!",
  },
  {
    name: "Bethel Chanyalew",
    promptIdx: 5,
    bookTitle: "Beloved",
    bookAuthor: "Francis Chan",
    videoUrl: "https://drive.google.com/file/d/1SmwjmTTbH1XdjaJW7PoDp1hh-sn5xIvJ/view?usp=share_link",
    note: "From our very first conversation, the Lord has used Pam to remind and teach me what it means to simply be loved by Him; something that sounds so simple, yet so healing to my heart, so different than what I have been used to, and at a time when life was indeed hard. From her encouragements, prayers, and willingness to let us into her home, God has continued to use her heart and her kindness as a vessel of His love...nothing to be earned or to work for or even given on the basis of how long we have known her (or Him). Plus, she had recommended Crazy Love by Francis Chan to me a few months back so it felt very fitting that this would be the follow up haha! <3",
  },
  {
    name: "Remi Ham",
    promptIdx: 4,
    bookTitle: "All Along You Were Blooming",
    bookAuthor: "Morgan Harper Nichols",
    videoUrl: "https://drive.google.com/file/d/1jcrAzEV7-WzwNZYeUhLmLHMztN9tADWS/view?usp=share_link",
    note: "In almost every other conversation, Pam checks in with a statement - Remi, I can't wait to hear about the big dreams that you have for yourself. That's a testament to the type of woman and friend she is. Always rooting for others, asking because she genuinely cares, and wanting to see her friend's dreams visualized. And I want that for her. I can't wait to see how she continues to bloom. I chose the book, All Along You Were Blooming, because it's great reminder that we're always growing, to be grateful for ALL blooming seasons, and not to be scared to take bold steps forward. You continue to teach me that life is too short not to dream big, and I want that for you my friend. I'm always your cheerleader and I love you deep!",
  },
  {
    name: "Mama T",
    promptIdx: 10,
    bookTitle: "Women of the Bible",
    bookAuthor: "Karajah Yashar",
    videoUrl: "https://drive.google.com/file/d/11dWvMQDoY2l76PnPbodJ0nflWt8NkVq0/view?usp=share_link",
    note: "Pam knows that Victory is hers in all she set her mind to, because she knows God is always by her side!!",
  },
  {
    name: "Amber Aughtry-Lindsay",
    promptIdx: 0,
    bookTitle: "Reel/Black Cake",
    bookAuthor: "Kennedy Ryan/Charmaine Wilkerson",
    videoUrl: "https://drive.google.com/file/d/1yEplko73UQgX42qTWlUUNBycf-lVOhlz/view?usp=share_link",
    note: "Pam you are unapologetically real and honest! But also super sweet and tender with everyone!",
  },
  {
    name: "Sarah Anum",
    promptIdx: 2,
    bookTitle: "Seeing and Savoring Jesus",
    bookAuthor: "John Piper",
    videoUrl: "https://drive.google.com/file/d/1w1dTpuVOo2mTGD0iczhAbP0VdaE6NPnw/view?usp=share_link",
    note: "I chose Seeing and Savoring Jesus for you, because that\u2019s exactly what I see you doing \u2013 that\u2019s how I see you living your life. You have this beautiful way of looking for God\u2019s hand in everything, and not just noticing it, but truly savoring His presence and His handiwork.\n\nYou move through life slowly and deliberately, with such thoughtfulness, never wanting to miss even the smallest piece of what Jesus has for you. I love that about you. It\u2019s inspiring, grounding, and deeply genuine.\n\nLet Me Be a Woman you gave to me to read years ago and I\u2019ve read through it twice. You have 4 little women you are discipling so I figured you\u2019d need this again.",
  },
  {
    name: "Jessica Jones",
    promptIdx: 0,
    bookTitle: "Take my hand",
    bookAuthor: "Dolen Perkins-Valdez",
    videoUrl: "https://drive.google.com/file/d/1q4b1fbIkEod4F6JBF0WTxU2TnRvHzWQ9/view?usp=share_link",
    note: "This book is connected to African-American women\u2019s health issues that made me think of you. The title also spoke to me. The woman who is the \u201cmain character\u201d (it\u2019s based on a true story) started down a path and uncovered something that shifted her work and ultimately shaped her calling. I see how you keep walking by faith and I also see how your work and calling are being shaped and honed as you walk by faith.",
  },
  {
    name: "Sara Tiegreen",
    promptIdx: 9,
    bookTitle: "Falling Upward",
    bookAuthor: "Richard Rohr",
    videoUrl: "https://drive.google.com/file/d/1FNPXy_KSnMUXSMLUquoYOVgmqLihTZTc/view?usp=share_link",
    note: "It\u2019s a book by my favorite theologian and is about a spiritual journey toward a life of integrity and meaning vs achievement and outward/cultural success, which resonates with the beautiful life I see you living and leading. There is also a companion journal for reflection and contemplation.",
  },
  {
    name: "Tiara",
    promptIdx: 10,
    bookTitle: "Where the wildflowers grow",
    bookAuthor: "Terah Shelton Harris",
    videoUrl: "https://drive.google.com/file/d/1_DEfsYEQH8N1GiVsyrRYa31VAmv6EI9E/view?usp=share_link",
    note: "I chose this book because the cover reminded me of Pam. The beauty and the flowers scream \u201cPam!\u201d",
  },
  {
    name: "Shannon Blankenship",
    promptIdx: 9,
    bookTitle: "The Giving Tree",
    bookAuthor: "Shel Silverstein",
    videoUrl: "https://drive.google.com/file/d/1TcRl_MLPnRnvBgZvx43q9pDqoDdMiUkt/view?usp=share_link",
    note: "The Giving Tree is about the unconditional love one has for another. Even though I\u2019ve only known Pam a short amount of time, I see the loving, joyfully giving, and strong woman she is. She selflessly pours into those around her and I am so blessed to call her a friend. Happy Birthday, Pam!",
  },
  {
    name: "Melissa Sloop",
    promptIdx: 10,
    bookTitle: "The Gift of Being Yourself",
    bookAuthor: "David Benner",
    videoUrl: "https://drive.google.com/file/d/1IU_ys7BKM_zW4eemzk-_vHaErpYl7qdz/view?usp=share_link",
    note: "Pam, you embody the message of this book, because you embody the FREEDOM and humility that come when we relax into the process of allowing God to form us into who he designed us to be, and the continual journey of deepening our union with Jesus. Thank you for being YOU!!!",
  },
  {
    name: "Keandra Ewing",
    promptIdx: 6,
    bookTitle: "Black Joy Playbook",
    bookAuthor: "Tracey Michael Lewis-Giggetts",
    videoUrl: "https://drive.google.com/file/d/1TxJOrPOQe-Sy6HBTh05ei9gZ5vbzrQLU/view?usp=share_link",
    note: "Pam embodies black joy and I always experience joy and laughter when we are together. The joy of the Lord is indeed her strength.",
  },
  {
    name: "Shawn Friday",
    promptIdx: 1,
    bookTitle: "Love Song to the Nation",
    bookAuthor: "Bell Hooks",
    videoUrl: "https://drive.google.com/file/d/1PFIkMLb99DRrtCp4mo7Bp6xRj75WsF_n/view?usp=share_link",
    note: "I first read All About Love (part 1) in college and I believe it speaks to how my sister views love; not the perversion we get from society, media, and culture. Love is more than a feeling, its intentional conscious practices. I think my sister is the epitome of how love is described by hooks, and how Paul describes the 16 attributes of love. Pam has given me perspective on how to view and love over the years of our friendship, and not just with my mess and trauma, but with her own experiences. I\u2019m thankful for that. She\u2019s taught me that\u2019s what life is really all about- love. When life gets hard for me she shows up and shows nothing but love, and I know her daughters will grow up and understand that their mother was Always All About Love. Book one challenges and discusses wordly love and goes deeper into how love can heal. Pam is a healer, advocate, counselor. I hope this series adds more to her cup.",
  },
  {
    name: "Natalie A. Collier",
    promptIdx: 10,
    bookTitle: "Life is Short but Wide",
    bookAuthor: "J. California Cooper",
    videoUrl: "https://drive.google.com/file/d/1guVuqoCDzG-rYqb8ugJjBZ2C29j-prlM/view?usp=share_link",
    note: "It\u2019s a story of faith, perseverance, wonder and abundance \u2014 like she is.",
  },
  {
    name: "Kyla K",
    promptIdx: 3,
    bookTitle: "Fervent: A woman\u2019s Battle Plan for serious, specific and strategic prayer",
    bookAuthor: "Priscilla Shirer",
    videoUrl: "https://drive.google.com/file/d/1FgUQ8lArConO8NJs9BhPGujVqoEiyhiO/view?usp=share_link",
    note: "Over the years through all of your victories and valleys, I have seen you show intense, sincere, and passionate faith, character, and love. That fervent nature has revealed your strength, your enthusiasm, and your determination. You are a mighty woman of God and every woman needs a battle strategy. I hope you love this book. Happy birthday sis!",
  },
  {
    name: "Clarissa Bridges",
    promptIdx: 6,
    bookTitle: "The King Arthur Baking Company\u2019s All Purpose Baking Companion",
    bookAuthor: "King Arthur Baking Company",
    videoUrl: "https://drive.google.com/file/d/1kK2Y9HxIfWIzoqma6XDlul_FNr7I7OVY/view?usp=share_link",
    note: "Pam loves to bake, and I know this is a book she\u2019ll keep coming back to over the years. I can already picture her using it to make memories with her family, her friends, and the people she serves. Whether it\u2019s for a special occasion, a random Sunday morning, or just experimenting in the kitchen with her beautiful daughters, I know this book will be a part of those moments.",
  },
  {
    name: "Macaela Campbell",
    promptIdx: 10,
    bookTitle: "Ministry in the Image of God",
    bookAuthor: "Stephen Seamands",
    videoUrl: "https://drive.google.com/file/d/1XBla-rk5BmgbH6Ty60yB-RNU5ayovANy/view?usp=share_link",
    note: "Because the way you live\u2026 you carry yourself like someone who already knows what it means to reflect God.",
  },
  {
    name: "Maya Metz",
    promptIdx: 6,
    bookTitle: "The Creative Act: A Way of Being",
    bookAuthor: "Ric Rubin",
    videoUrl: "https://drive.google.com/file/d/1Xwb3ln1HzTn2xPa7gu-MKKDqV4nT0tbB/view?usp=share_link",
    note: "She brings creativity to everything around her.",
  },
  {
    name: "Amy Johnson",
    promptIdx: 0,
    bookTitle: "Kin",
    bookAuthor: "Tayari Jones",
    videoUrl: "https://drive.google.com/file/d/19KqYoHwK7Dyie8b0IB4h9IyG7ACLDVze/view?usp=share_link",
    note: "Because of the way we\u2019ve so easily and deeply become \u201ckin.\u201d I\u2019m so grateful for the safety, familiarity, and full out foolishness we have found in our sisterhood\u2026our God-given kinship.",
  },
  {
    name: "Janice T. Thompson",
    promptIdx: 8,
    bookTitle: "The Substance of Things Hoped For",
    bookAuthor: "Samuel DeWitt Proctor",
    videoUrl: "https://drive.google.com/file/d/1GZCs7epnQp0qv2bN8-CcNw6uIn4qO0-6/view?usp=share_link",
    note: "I chose this book because it reflects Pam\u2019s expressive hope and evidence of faith.",
  },
  {
    name: "Supa Chris",
    promptIdx: 8,
    bookTitle: "All Along You Were Blooming",
    bookAuthor: "Morgan Harper Nichols",
    videoUrl: "https://drive.google.com/file/d/1CXisxlVFGFk0bYm7-hClqWvSTvvqKBGa/view?usp=share_link",
    note: "Because the cover is beautiful and the title affirms the process of life - all long Pam is becoming who Pam is meant to be through every season - through the good and through the hard. Through the beautiful and the ugly. You bloom.",
  },
  {
    name: "Gabrielle Eitienne",
    promptIdx: 0,
    bookTitle: "Vibration Cooking or The Travel Notes of a Geechee Girl",
    bookAuthor: "Vertamae Smart-Grosvenor",
    videoUrl: "https://drive.google.com/file/d/1UvxGHE-QbbmL-lza3W8tM96bs3eGXzfx/view?usp=share_link",
    note: "Because It was effortless from the very beginning with you Pams.",
  },
  {
    name: "Auntie Reeeeeeey",
    promptIdx: 3,
    bookTitle: "All Along You Were Blooming: Thoughts for Boundless Living",
    bookAuthor: "Morgan Harper Nichols",
    videoUrl: "https://drive.google.com/file/d/1qkLL1b_NC9T25HetrVDg6CTUVCVY2-X-/view?usp=share_link",
    note: "Pam embodies Morgan Harper Nichols\u2019 encouraging words by living her life surrendered to Christ. I thought for once, she might be the one who needs encouragement and a chance to rest from being the encourager. Even more, Pam\u2019s deep appreciation for the arts, scripture, and cultural relevance makes this book an ideal choice that embodies these characteristics.",
  },
  {
    name: "Carla Williams",
    promptIdx: 2,
    bookTitle: "I Surrender All",
    bookAuthor: "Priscilla Shirer",
    videoUrl: "https://drive.google.com/file/d/1qvh59vk-puWYF2oEyEudHRqJ3rTSetMZ/view?usp=share_link",
    note: "I truly believe the God will answer all the concerns, questions, heartaches, challenges and more when we surrender all to Him. I pray this over Pam\u2019s life not only now but for decades to come!",
  },
];
